proxy:
  title: Open Analytics Shiny Proxy
  logo-url: https://www.openanalytics.eu/shinyproxy/logo.png
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  authentication: ldap
  admin-groups: scientists
  # Example: 'ldap' authentication configuration
  ldap:
    url: "ldap://corp.ads.arkit.com:389/DC=corp,DC=ads,DC=arkit,DC=com"
    user-search-filter: (sAMAccountName={0})
    group-search-base: OU=Groups,OU=India
    group-search-filter: (member={0})
    manager-dn: admin@corp.ads.arkit.com
    manager-password: Password123
    # Docker configuration
  docker:
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
  - id: 06_tabsets
    container-cmd: ["R", "-e", "shinyproxy::run_06_tabsets()"]
    container-image: openanalytics/shinyproxy-demo

logging:
  level:
    root: DEBUG
  file:
    /var/log/shinyproxy.log
